name: Java Acceptance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  acceptance-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Start the application
      run: mvn exec:java -Dexec.mainClass="Main"

    - name: Wait for application to start
      run: sleep 30s

    - name: Run Acceptance Tests with Maven
      run: mvn verify -P acceptance-tests
