name: Java Integration Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Start the application
      run: mvn spring-boot:run &

    - name: Wait for application to start
      run: |
        retries=30
        until curl --output /dev/null --silent --head --fail http://localhost:8080/actuator/health || [ $retries -eq 0 ]
        sleep 5s

    - name: Run Integration Tests with Maven
      run: mvn verify -P integration-tests
